
apply plugin: 'maven-publish'


task javadocJar(type: Jar) {
    from javadoc
    archiveClassifier = 'javadoc'
}
task sourcesJar(type: Jar) {
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java

            artifact javadocJar
            artifact sourcesJar

            pom {
                resolveStrategy = Closure.DELEGATE_FIRST

                description = "Set of plugins to handle frames in one system"
                name = "frameswork"
                url = "https://git.sciprog.center/InsanusMokrassar/frameswork"

                scm {
                    developerConnection = "scm:git:[fetch=]https://git.sciprog.center/InsanusMokrassar/frameswork.git[push=]https://git.sciprog.center/InsanusMokrassar/frameswork.git"
                    url = "https://git.sciprog.center/InsanusMokrassar/frameswork.git"
                }

                developers {
                    
                        developer {
                            id = "InsanusMokrassar"
                            name = "Ovsiannikov Aleksei"
                            email = "john.doe@inmo.dev"
                        }
                    
                }

                licenses {
                    
                        license {
                            name = "Apache Software License 2.0"
                            url = "https://opensource.org/licenses/Apache-2.0"
                        }
                    
                }
            }
        }
    }
    repositories {
        if ((project.hasProperty('SCIPROG_USER') || System.getenv('SCIPROG_USER') != null) && (project.hasProperty('SCIPROG_PASSWORD') || System.getenv('SCIPROG_PASSWORD') != null)) {
            maven {
                name = "SCIProg"
                url = uri("https://maven.sciprog.center/kscience")
        
                credentials {
                    username = project.hasProperty('SCIPROG_USER') ? project.property('SCIPROG_USER') : System.getenv('SCIPROG_USER')
                    password = project.hasProperty('SCIPROG_PASSWORD') ? project.property('SCIPROG_PASSWORD') : System.getenv('SCIPROG_PASSWORD')
                }
            }
        }
        if ((project.hasProperty('SONATYPE_USER') || System.getenv('SONATYPE_USER') != null) && (project.hasProperty('SONATYPE_PASSWORD') || System.getenv('SONATYPE_PASSWORD') != null)) {
            maven {
                name = "sonatype"
                url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
        
                credentials {
                    username = project.hasProperty('SONATYPE_USER') ? project.property('SONATYPE_USER') : System.getenv('SONATYPE_USER')
                    password = project.hasProperty('SONATYPE_PASSWORD') ? project.property('SONATYPE_PASSWORD') : System.getenv('SONATYPE_PASSWORD')
                }
            }
        }
    }
}

if (project.hasProperty("signing.gnupg.keyName")) {
    apply plugin: 'signing'

    signing {
        useGpgCmd()

        sign publishing.publications
    }

    task signAll {
        tasks.withType(Sign).forEach {
            dependsOn(it)
        }
    }

    // Workaround to make android sign operations depend on signing tasks
    project.getTasks().withType(AbstractPublishToMaven.class).configureEach {
        def signingTasks = project.getTasks().withType(Sign.class)
        mustRunAfter(signingTasks)
    }
    // Workaround to make test tasks use sign
    project.getTasks().withType(Sign.class).configureEach { signTask ->
        def withoutSign = (signTask.name.startsWith("sign") ? signTask.name.minus("sign") : signTask.name)
        def pubName = withoutSign.endsWith("Publication") ? withoutSign.substring(0, withoutSign.length() - "Publication".length()) : withoutSign
        // These tasks only exist for native targets, hence findByName() to avoid trying to find them for other targets

        // Task ':linkDebugTest<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
        def debugTestTask = tasks.findByName("linkDebugTest$pubName")
        if (debugTestTask != null) {
            signTask.mustRunAfter(debugTestTask)
        }
        // Task ':compileTestKotlin<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
        def testTask = tasks.findByName("compileTestKotlin$pubName")
        if (testTask != null) {
            signTask.mustRunAfter(testTask)
        }
    }
}
