plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
}

apply from: "$mppJavaProject"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":frameswork.features.processor.common")
                api project(":frameswork.features.common.server")
            }
        }

        jvmMain {
            dependencies {
                api libs.scrimage
            }
        }
    }
}