plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    alias(libs.plugins.compose)
    alias(libs.plugins.kt.compose)
}

apply from: "$mppJsWithCompose"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":frameswork.features.frames.common")
                api project(":frameswork.features.common.web")
            }
        }
    }
}